# Generated by Django 4.0.3 on 2022-03-08 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('duration', models.IntegerField(default=1)),
                ('description', models.TextField(default='Insert Description')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('res_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.type')),
            ],
        ),
    ]
