# Generated by Django 4.0.3 on 2022-03-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ResType',
        ),
    ]
